name: 'nbdev-ci'
description: 'Test with nbdev'
inputs:
  pre:
    description: 'Install prerelease nbdev/execnb from master?'
    required: false
    default: ''
  version:
    description: 'Version of python to set up'
    required: false
    default: '3.9'

runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.version }}
        cache: "pip"
        cache-dependency-path: settings.ini
    - name: Install deps, check cleaned
      env:
        USE_PRE: ${{ inputs.pre }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ $USE_PRE ]; then
          pip install -U git+https://github.com/fastai/fastcore.git
          pip install -U git+https://github.com/fastai/execnb.git
          pip install -U git+https://github.com/fastai/nbdev.git
        else
          pip install -U nbdev
        fi
        pip install -qe ".[dev]"
        echo "Check we are starting with clean git checkout"
        git update-index --assume-unchanged */_modidx.py
        if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
        echo "Trying to strip out notebooks"
        nbdev_clean
        echo "Check that strip out was unnecessary"
        git status -s # display the status to see which nbs need cleaning up
        if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"; false; fi
    - name: Check if notebooks are synced
      shell: bash
      run: |
        nbdev_export
        if [ -n "$(git status -uno -s)" ]; then
          echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
          git status -uno -s
          git diff
          exit 1;
        fi
    - name: Test Notebooks
      shell: bash      
      run: nbdev_test

