name: 'check sync nb'
description: 'Make sure notebooks are in sync and cleaned'
inputs:
  DUMMY:
    description: 'dummy input so this workflow will work.  No input is required.'
    required: false
runs:
  using: "composite"
  steps: 
    - name: change folders
      run: |
        mkdir fastaiworkflow_temp_files
        cd fastaiworkflow_temp_files
      shell: bash
    - name: see path
      run: |
        pwd
        ls
      shell: bash
#     - name: Python
#       run: |
#         from foo import bar
#         bar()
#       shell: python

