name: 'build-docs'
description: 'Create docs with nbdev'
inputs:
  pre:
    description: 'Install prerelease nbdev/execnb from master?'
    required: false
    default: ''
  version:
    description: 'Version of python to set up'
    required: false
    default: '3.12'
  ghtoken:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false
  publish_branch:
    description: 'Branch name to publish docs to'
    required: false
    default: 'gh-pages'
  torch_cpu:
    description: "Install PyTorch CPU instead of PyTorch Cuda.  Has no effect if PyTorch isn't a requirement.  Enabled by defaut."
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}
        cache: "pip"
        cache-dependency-path: settings.ini
    - name: Install Dependencies
      env:
        USE_PRE: ${{ inputs.pre }}
        TORCH_CPU: "${{ inputs.torch_cpu }}"
      shell: bash
      run: |
        set -ux
        python -m pip install --upgrade pip
        pip install -Uq "nbdev<3"
        if [ $TORCH_CPU ]; then
          test -f setup.py && pip install -e ".[dev]" --extra-index-url https://download.pytorch.org/whl/cpu
        else
          test -f setup.py && pip install -e ".[dev]"
        fi
        nbdev_docs
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.ghtoken }}
        force_orphan: true
        publish_dir: ./_docs
        # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
        # You can swap them out with your own user credentials.
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
        publish_branch: ${{ inputs.publish_branch }}

