name: 'quarto-rsync'
description: 'Create docs with nbdev'
inputs:
  username:
    description: 'rsync user'
    required: true
  hostname:
    description: 'rsync host'
    required: true
  dest_path:
    description: 'path to rsync to'
    required: true
  ssh_key:
    description: "SSH key for rsync" 
    required: true
  delete:
    description: "Toggle the --delete flag on or off for rsync.  Set to any value to enable.  Disabled by default."
    required: false
    default: ''
  pre:
    description: 'Install prerelease nbdev/execnb from master?'
    required: false
    default: ''
runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install deps, build docs, and sync
      env:
        SSH_KEY: ${{ inputs.ssh_key }}
        USE_PRE: ${{ inputs.pre }}
        delete: "${{ inputs.delete }}"
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        echo -e 'Host *\n  StrictHostKeyChecking no' > ~/.ssh/config
        chmod 600 ~/.ssh/*
        python -m pip install --upgrade pip
        if [ $USE_PRE ]; then
          pip install -U git+https://github.com/fastai/fastcore.git
          pip install -U git+https://github.com/fastai/execnb.git
          pip install -U git+https://github.com/fastai/nbdev.git
        else
          pip install -U nbdev
        fi
        pip install -e ".[dev]"
        # Use prerelease until v1.1 available
        wget -nv https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.75/quarto-1.1.75-linux-amd64.deb
        sudo dpkg -i quarto*.deb
        nbdev_docs
        rsync $(echo ${delete:+'--delete'}) -az _docs/ ${{ inputs.username }}@${{ inputs.hostname }}:${{ inputs.dest_path }}/
      shell: bash

