name: 'build-docs'
description: 'Create docs with nbdev'
inputs:
  username:
    description: 'rsync user'
    required: true
  hostname:
    description: 'rsync host'
    required: true
  dest_path:
    description: 'path to rsync to'
    required: true
  ssh_key:
    description: "SSH key for rsync" 
    required: true
  delete:
    description: "Toggle the --delete flag on or off for rsync.  Set to any value to enable.  Disabled by default."
    required: false
    default: ''
runs:
  using: "composite"
  steps: 
    - name: Setup ssh
      env:
        SSH_KEY: ${{ inputs.ssh_key }}
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        echo -e 'Host *\n  StrictHostKeyChecking no' > ~/.ssh/config
        chmod 600 ~/.ssh/*
      shell: bash
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U --pre nbdev
        pip install -e ".[dev]"
      shell: bash
    - name: Create docs
      env:
        delete: "${{ inputs.delete }}"
      run: |
        nbdev_docs
        rsync $(echo ${delete:+'--delete'}) -az _docs/ ${{ inputs.username }}@${{ inputs.hostname }}:${{ inputs.dest_path }}/
      shell: bash

