name: 'docs'
description: 'deploy docs to static host'
inputs:
  ssh_key:
    description: 'private key'
    required: true
  ssh_config:
    description: 'ssh config'
    required: true
  dest_hostname:
    description: 'hostname to rsync to'
    required: false
    default: 'dochost'
  dest_path:
    description: 'part on host to rsync files to'
    required: true
runs:
  using: "composite"
  steps: 
    - name: install rsync
      run: |
        apt-get update && apt-get install -y rsync
      shell: bash
    - name: rsync
      run: |
        export HOME=/root
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_key }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        echo "${{ inputs.ssh_config }}" > ~/.ssh/config
        chmod 400 ~/.ssh/config
        chmod 700 ~/.ssh
        rsync -az docs/_site/ ${{ inputs.dest_hostname }}:${{ inputs.dest_path }}
      shell: bash
