name: 'docs'
description: 'deploy docs to static host'
inputs:
  ssh_key:
    description: 'private key'
    required: true
  ssh_config:
    description: 'ssh config'
    required: true
  hostname:
    description: 'hostname to rsync to'
    required: true
  username:
    description: 'username to use for rsync'
    required: true
  path:
    description: 'path on host to rsync files to'
    required: false
    default: ''
runs:
  using: "composite"
  steps: 
    - name: install rsync
      run: |
        apt-get update && apt-get install -y rsync
      shell: bash
    - name: rsync
      run: |
        export HOME=/root
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_key }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        rsync -e "ssh -o StrictHostKeyChecking=no" -az docs/_site/ ${{ inputs.username}}@${{ inputs.hostname }}:${{ inputs.path }}
      shell: bash
