name: 'build-docs'
description: 'Create docs with nbdev'
inputs:
  username:
    description: 'rsync user'
    required: true
  hostname:
    description: 'rsync host'
    required: true
  dest_path:
    description: 'path to rsync to'
    required: true
  ssh_key:
    description: "SSH key for rsync" 
    required: true
runs:
  using: "composite"
  steps: 
    - name: Create docs
      shell: bash
      env:
        JEKYLL_ENV: 'production'
        SSH_KEY: ${{ inputs.ssh_key }}
      run: |
        cp -r docs_src docs
        pip install -Uqq nbdev fastcore
        pip install -e .[dev]
        nbdev_build_docs
        cd docs 
        bundle i
        bundle exec jekyll build --strict_front_matter
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        rsync -az _site/ ${{ inputs.username }}@${{ inputs.hostname }}:${{ inputs.dest_path }}/
