name: 'conda-env'
description: 'Set up conda env'
inputs:
  username:
    description: 'rsync user'
    required: true
  hostname:
    description: 'rsync host'
    required: true
  dest_path:
    description: 'path to rsync to'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Create docs
      env:
        JEKYLL_ENV: 'production'
        SSH_KEY: ${{ secrets.DH_KEY }}
      run: |
        cp -r docs_src docs
        nbdev_build_docs
        cd docs 
        bundle i
        bundle exec jekyll build --strict_front_matter
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        rsync -az _site/ ${{ username }}@${{ hostname }}:${{ dest_path }}/
