on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test-open-issue
    steps:
    - uses: actions/setup-python@v2
    - name: where are we?
      run: pwd
    - uses: fastai/workflows/open_issue@master
      
